name: Deploy airbase volleyball website

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch
  
  workflow_dispatch:  # Enable manual triggering of the workflow

permissions:
  contents: write  # Grant permission to write to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # You can specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Assuming you have a build script in your package.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
          publish_dir: ./_site
